extends Resource
class_name SplashData

var texts=["Play Mariposa!","Drink Milk!","Call Your Mom!","Play Hangman!","Play Baby Delulu!",
	"Play Chambers of Ket!","Play Hailstorm!","Play Robo Dolphin Escape!","Play the Great Snack Heist!",
	"Play Chasing Shadows!","Play Stellar Service!","Play Let's Go Crambling!","Play Stratagem",
	"Play Fishing with Goober!","Play Tail of Two!","Play Same Day Delivery!","Play Paper Heart!",
	"Play Spellthief!","Go Outside!","Study for that Midterm!","Pet a Dog!","Don't Play Valorant!",
	"It’s Baarific!","Baaa!", "Land of the Baaaa", "No Baaaaad sheeps allowed!", "Lamb Chops",
	"Stop Baaaabbling and just play!", "Help grow the Wooly Community!", "Dont be on the lamb and play this game!",
	"Avoid the Baaaackrooms!", "Dont be a baaackstaber", "Baaaagels are a\ntype of bread", "Always have a baaaagful\nof bread!",
	"Play Cult of the Lamb!","Remember to drink water!",
	"You're doing great, probably!",
	"Smile at a stranger today!",
	"Don’t forget to stretch!",
	"Failure is just data collection!",
	"Have you eaten something green today?",
	"Deep breaths fix more than you think.",
	"Pet a cat if available.",
	"You’re someone’s favorite NPC!",
	"Even small steps count!",
	"Try again tomorrow — it’s free!",
	"Nobody really knows what they’re doing.",
	"The moon called — it said you’re cool.",
	"Hydration is the ultimate buff.",
	"Be kind, rewind.",
	"It’s okay to take breaks!",
	"Chaos is temporary, snacks are forever.",
	"Don’t let perfection delay progress.",
	"Today’s mood: cautiously optimistic.",
	"Your pace is valid.",
	"Clean desk, clear mind!",
	"Forgive yourself like you forgive others.",
	"Small joys > big worries.",
	"You’ve survived 100% of your bad days.",
	"Don’t text your ex — bake bread instead.",
	"Nap like no one’s watching.",
	"Growth looks messy — it’s working!",
	"Dreams need snacks too.",
	"Keep your heart weird.",
	"Make your bed, it’s free serotonin!",
	"Be the plot twist you needed.",
	"Coffee counts as emotional support.",
	"Progress, not perfection!",
	"Remember: clouds aren’t mistakes.",
	"Do one nice thing for Future You.",
	"Kindness is a renewable resource!",
	"Plants grow slowly too.",
	"You are the DLC life needed!",
	"Sometimes ‘good enough’ is perfect.",
	"Start small, stay curious."]
